//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodiesWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderId { get; set; }
        public int CustomerId { get; set; }
        public int FoodItemId { get; set; }
        public int VendorId { get; set; }
        public int OrderQuantity { get; set; }
        public int OrderAmount { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public string OrderLocation { get; set; }
        public string OrderStatus { get; set; }
        public string OrderComments { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
