//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKDbAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKChallangedDecision
    {
        public string BLNumber { get; set; }
        public string ConcerningRightsIn { get; set; }
        public string HearingOfficer { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string PersonOrCompanyInvolved { get; set; }
        public string ProvisionsDiscussion { get; set; }
        public string HearingType { get; set; }
        public string Keywords { get; set; }
        public string RelatedDecisions { get; set; }
        public string Summary { get; set; }
        public string PdfLink { get; set; }
        public string Status { get; set; }
    }
}
