//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKDbAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKChallangeDecision
    {
        public string BL_number { get; set; }
        public string Concerning_rights_in { get; set; }
        public string Hearing_Officer { get; set; }
        public Nullable<System.DateTime> Decision_date { get; set; }
        public string Person_s__or_Company_s__involved { get; set; }
        public string Provisions_discussed { get; set; }
        public string Keywords { get; set; }
        public string Related_Decisions { get; set; }
        public string Summary { get; set; }
        public string PdfLink { get; set; }
    }
}
